### ISSUE TITLE
Mage Arcane Charges with counter

### ISSUE THREAD

**Issue by BOLLE007xp** [Adirelle/AdiButtonAuras#141]
is it possible to show the debuff of "Arcane Charge" (debuff id: 114664) with duration and count of stacks in the button of "Arcane Blast" (spell id: 30451) like inline aura did?

**Comment by Adirelle** [comment]
Shouldn't Arcane Charge be shown on the consummers, i.e. Arcane Barrage and Evocation ?

**Comment by Rainrider** [comment]
@BOLLE007xp any thoughts on that?

**Comment by leginnoslen** [comment]
I am also interested in something like this but I am not smart enough to figure out how to script it. I have tried for an hour to get my Arcane Charges to show on my Arcane Barrage button but I have no idea where to begin, and this is all very frustrating because it seems like it should be really simple.
