### ISSUE TITLE
(Druid) Connect Spells Mangle/ Solar/ Vortex/ Mushroom/ Charge / Typhoon

### ISSUE THREAD

**Issue by Tonyleila** [Adirelle/AdiButtonAuras#160]
1 Wild Mushroom
Spell in Bar: 88747
Buff on self (max 3 Stacks): 88747 http://www.wowhead.com/spell=88747/wild-mushroom

2 Ursol's Vortex
Spell in Bars: 102793  http://www.wowhead.com/spell=102793/ursols-vortex
Spell on target: 127797

3 Solar Beam
Silenced 8 sec remaining is now showing up as target debuff

4 Mangle
Spell in Bar 33917 http://www.wowhead.com/spell=33917/mangle
Debuff on target: 58180 http://www.wowhead.com/spell=58180/infected-wounds

5 Wild Charge
Spell in bars: 49376 http://www.wowhead.com/spell=49376/wild-charge
Debuff in target: 50259 http://www.wowhead.com/spell=50259/dazed

6 Typhoon
Spell in bars: 132469 http://www.wowhead.com/spell=132469/typhoon
Debuff on target: 61391 http://www.wowhead.com/spell=61391/typhoon

**Comment by Adirelle** [comment]
1. Added.
2. Added.
3. Is there a target debuff ? If not there is no way to show it.
4. Added.
5. The debuff seems too common.
6. Added.

**Comment by Tonyleila** [comment]
3. Sorry shure there is but its not showing a timer ingame: 81261 http://www.wowhead.com/spell=81261/solar-beam

**Comment by Adirelle** [comment]
Yes, because it's positional. We could show the debuff without a timer.

**Comment by Tonyleila** [comment]
1, 2, 3, 5, and 6 have not been added yet or they are not working :( Just tested on my druid...

**Comment by Rainrider** [comment]
Ursol's Vortex was functioning ok, same explanation as for solar beam above - it is positional, is lasts as long as the target is in the area of effect - so it does not display a timer, just the "bad" border.

**Comment by Tonyleila** [comment]
Hmmm I have disabled the bad border for all spells, any way to make spells that have just the border and no text display a text indicator that they are active? Maybe a + or something like this.

**Comment by Rainrider** [comment]
Nope. A lot of spells work like that though. Why would you deactivate the "bad" border?

**Comment by Tonyleila** [comment]
Because they look "bad" with my masque skin :P

**Comment by Rainrider** [comment]
Well thank you for spending hours verifying that stuff you reported as broken actually works :)

Choose another skin or another border type.

**Comment by Tonyleila** [comment]
Not shure if this was an ironic answer?
If its not possible the show the bad borders only for spells that have no timers I'll stay with just no info on this spells. My masque skin has a one pixel border and I realy don't want aba to show borders everywhere :S

**Comment by Tonyleila** [comment]
BTW  Solar Beam dosen't show a Bad border there is no rule for it, its just flashing when you are able to interrupt.

**Comment by Tonyleila** [comment]
But I'm still a bit confused, why can Solar Beam now have this very nice one pixel "bad" border while Ursol's Vortex has the ugly border that I selected with aba???
![border](https://cloud.githubusercontent.com/assets/756451/6617204/a5a7df68-c8b6-11e4-9443-20b84394b632.jpg)

**Comment by Rainrider** [comment]
Well, I don't want to go that much into deployment chains as it is not a very interesting info for you, but as I previously said (in another issue), I have to push a version tag for ABA on wowace so that it picks up updated libraries and bundles the zip package for download on wowace and curse.com. This is still not the case for reasons I already mentioned. I have pushed an alpha release of LibPlayerSpells-1.0 though, which contains the druid fixes that you can see in this very issue and you can download it as a separate addon either from wowace or from curse. If you use the curse updater or downloader or whatever it is called, you need to set it up to pick alpha versions as well, which is probably not a good recommendation. So, if you want to always have the latest development on this, you'd better manually download the nolib package from wowace and install the libraries separately. If you don't know how to do this, then please don't as I won't provide support for it. In that case you will have to wait until I push a new ABA release to wowace.

Before you ask why I close issues you are not able to easily verify are currently working, this is the answer: github is used as a development platform. So it is a way for us to track progress and mark progress from where it is done. It is not a tool for deployment (though git can be used that way too, but this is intended for developers).

So yes, the whole is probably not the best thing from a user perspective but it is the only way we could do it somewhat efficiently. Believe me, I do appreciate the feedback you provide, but please bring in some patience as well.

**Comment by Rainrider** [comment]
As for the other issue with the borders:
If you unckeck "Use Masque" in ABA, then the ABA highlight texture you picked from the dropdown is used. If you check "Use Masque" then the borders provided by its skin are used.

Masque has options per addon that supports it and maybe even per action bar, so check if both bars use the same skin. Honestly I don't know, but I don't think this is an ABA issue and you'd either ask the masque or the skin developer.

**Comment by Tonyleila** [comment]
Thanks for the reply :)
