### ISSUE TITLE
(Shaman)  Lightning Shield / Earth Shock / Lava Burst

### ISSUE THREAD

**Issue by Tonyleila** [Adirelle/AdiButtonAuras#161]
1 Lightning Shield is not showing up as Timer instead it only shows a 1 guess thats a stack because its not going away when I cast it on myself
Buff in my bars is same as buff: 324
http://www.wowhead.com/spell=324/lightning-shield
Instead it coud show http://www.wowhead.com/spell=142912/glyph-of-lightning-shield

2 Earth Shock
For some reason it shows buff stacks of Lightning Shield but there can only be one stack
http://www.wowhead.com/spell=8042/earth-shock

3 Lava Burst
Spell in Bars: 51505 http://www.wowhead.com/spell=51505/lava-burst
Buff on self: 77762: http://www.wowhead.com/spell=77762/lava-surge

**Comment by Adirelle** [comment]
1. The lightning shield lasts 1 hour and timers are hidden when above a configurable duration (10 minutes by default); check the configuration. The visible digit is caused by the API returning "one stack" for that spell. There is no way to tell the maximum number of charges.

2. Same issue with charge as 1.
