### ISSUE TITLE
Request: Death Knights - Diseases

### ISSUE THREAD

**Issue by Implied** [Adirelle/AdiButtonAuras#175]
Hi, I Google'd "Adi - Plague Leech" which lead me to this - https://github.com/Adirelle/AdiButtonAuras/issues/84 - & here.

Just bumping to bring a couple of issues to light - Outbreak & Plague Leech are both currently still completely grey'd out, not sure if the latter is intentional or not.

Also, similar issue with Breath of Sindragosa, we're still lacking an option to have it flash only when at full RP.

Everything else works like a charm though, special thanks for the Soul Reaper & Interrupts highlights, extremely handy.

**Comment by Rainrider** [comment]
Outbreak applies two debuffs at once. I can add this to LibPlayerSpells, however I doubt that displaying that information on Outbreak via ABA provides any benefit - keep in mind that only one timer can be displayed at any given time (normally the shorter one).

Plague Leech could be made into an ABA rule that checks if both diseases are on the target, then checks whether you have at least two empty runes and then displays a hint on the button. I don't know if that covers all the spell mechanics though: what about rune type preferences? Can the player affect which runes will get replenished if more that 2 are re-charging?

I am not sold on the idea of telling the player to use a 2 min CD because runic power is capped. I also don't see where we currently use a flash for Breath of Sindragosa. We only display the duration of the self-buff applied by it. Or do I misunderstand you?

**Comment by Implied** [comment]
I was thinking about it as more of a Bone Shield-style functionality ("Show the "good" border when your Bone Shield buff is found on yourself." - "Show the "good" border when at least one Disease (Frost Fever/Blood Plague/Necrotic Plague) is/are found on your target", but the Timer shouldn't be a problem I think, Outbreak applies both Debuffs at the same time, both Blood Plague & Frost Fever have the same duration, & extending one extends the other so the Timer should be accurate regardless of which it focuses on.

Plague Leech - For Blood, it seemingly prioritizes the Frost & Unholy Runes, in order to grant a Free Death Strike, only falling back to granting a Blood Death Rune when it fails to find a second Frost/Unholy Rune to give instead. Same for Frost (free Obliterate), whereas for Unholy it prioritizes Blood/Frost Runes (free Festering Strike), & falls back to granting an Unholy Death Rune if need be. It seems to follow the same ruleset as Blood Tap, if that helps.

Honestly the BoS thing, I just noticed it wasn't implemented, so I figured I'd mention it again. But yeah I see what you mean, it's about more than just "you're at 100 RP, it's off CD, & I'm making it green, so punch it!"

**Comment by Rainrider** [comment]
741dc8d2d88ea80d7aa7bdaf1dfa8864aa091061 adds a rule for Outbreak. I'll take a look at Plague Leech when the European Servers come back up.

**Comment by Implied** [comment]
Hi, yeah, Outbreak works like a charm with that Patch. Picks up Disease Duration, Disease Count, etc.

Though I noticed that without "Inverted", ABA will highlight Outbreak in red when Diseases are present on the Target, rather than when they're missing. Unless this is intended as a means of deterring further Outbreak-pushing?

**Comment by Rainrider** [comment]
Yes, this is the intended behavior:
  - red border, timer present, no stack count = only 1 of the 2 diseases is present, you probably want to save your outbreak CD and apply the absent disease by its own button
  - red border, timer present, stack count present (always 2) = both diseases are on the target, don't use outbreak

The Inverted option only applies to the border, so in that case probably not very handy.

**Comment by Rainrider** [comment]
d31629aba1473b0b3dd017070bde5839ff3ea775 adds the rule for Plague Leech. It only suggests using the spell when at least two runes are fully depleted. Please test and tell me if this is ok.

**Comment by Implied** [comment]
Hi sorry, weekend & all.

PL Patch works like a charm, thanks :D
